name: "Deploy"

on:
  push:
    branches: ["main"] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "acemmos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "generar binario"
      - run: echo "publicar version"
      - run: echo "publicar version en master" 